[package]
name = "aoc2024_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
regex = "1.11.1"
ndarray = "0.16.1"
rayon = "1.10.0"
itertools = "0.13.0"